# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.gudang_komoditas import GudangKomoditas  # noqa: F401,E501
from swagger_server import util


class Komoditas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, komoditas_id: int=None, nama: str=None, kategori: str=None, deskripsi: str=None, gudang_komoditas: GudangKomoditas=None, stok: int=None, nilai_pasar: int=None):  # noqa: E501
        """Komoditas - a model defined in Swagger

        :param komoditas_id: The komoditas_id of this Komoditas.  # noqa: E501
        :type komoditas_id: int
        :param nama: The nama of this Komoditas.  # noqa: E501
        :type nama: str
        :param kategori: The kategori of this Komoditas.  # noqa: E501
        :type kategori: str
        :param deskripsi: The deskripsi of this Komoditas.  # noqa: E501
        :type deskripsi: str
        :param gudang_komoditas: The gudang_komoditas of this Komoditas.  # noqa: E501
        :type gudang_komoditas: GudangKomoditas
        :param stok: The stok of this Komoditas.  # noqa: E501
        :type stok: int
        :param nilai_pasar: The nilai_pasar of this Komoditas.  # noqa: E501
        :type nilai_pasar: int
        """
        self.swagger_types = {
            'komoditas_id': int,
            'nama': str,
            'kategori': str,
            'deskripsi': str,
            'gudang_komoditas': GudangKomoditas,
            'stok': int,
            'nilai_pasar': int
        }

        self.attribute_map = {
            'komoditas_id': 'komoditas_id',
            'nama': 'nama',
            'kategori': 'kategori',
            'deskripsi': 'deskripsi',
            'gudang_komoditas': 'gudang_komoditas',
            'stok': 'stok',
            'nilai_pasar': 'nilai_pasar'
        }
        self._komoditas_id = komoditas_id
        self._nama = nama
        self._kategori = kategori
        self._deskripsi = deskripsi
        self._gudang_komoditas = gudang_komoditas
        self._stok = stok
        self._nilai_pasar = nilai_pasar

    @classmethod
    def from_dict(cls, dikt) -> 'Komoditas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Komoditas of this Komoditas.  # noqa: E501
        :rtype: Komoditas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def komoditas_id(self) -> int:
        """Gets the komoditas_id of this Komoditas.


        :return: The komoditas_id of this Komoditas.
        :rtype: int
        """
        return self._komoditas_id

    @komoditas_id.setter
    def komoditas_id(self, komoditas_id: int):
        """Sets the komoditas_id of this Komoditas.


        :param komoditas_id: The komoditas_id of this Komoditas.
        :type komoditas_id: int
        """

        self._komoditas_id = komoditas_id

    @property
    def nama(self) -> str:
        """Gets the nama of this Komoditas.


        :return: The nama of this Komoditas.
        :rtype: str
        """
        return self._nama

    @nama.setter
    def nama(self, nama: str):
        """Sets the nama of this Komoditas.


        :param nama: The nama of this Komoditas.
        :type nama: str
        """

        self._nama = nama

    @property
    def kategori(self) -> str:
        """Gets the kategori of this Komoditas.


        :return: The kategori of this Komoditas.
        :rtype: str
        """
        return self._kategori

    @kategori.setter
    def kategori(self, kategori: str):
        """Sets the kategori of this Komoditas.


        :param kategori: The kategori of this Komoditas.
        :type kategori: str
        """

        self._kategori = kategori

    @property
    def deskripsi(self) -> str:
        """Gets the deskripsi of this Komoditas.


        :return: The deskripsi of this Komoditas.
        :rtype: str
        """
        return self._deskripsi

    @deskripsi.setter
    def deskripsi(self, deskripsi: str):
        """Sets the deskripsi of this Komoditas.


        :param deskripsi: The deskripsi of this Komoditas.
        :type deskripsi: str
        """

        self._deskripsi = deskripsi

    @property
    def gudang_komoditas(self) -> GudangKomoditas:
        """Gets the gudang_komoditas of this Komoditas.


        :return: The gudang_komoditas of this Komoditas.
        :rtype: GudangKomoditas
        """
        return self._gudang_komoditas

    @gudang_komoditas.setter
    def gudang_komoditas(self, gudang_komoditas: GudangKomoditas):
        """Sets the gudang_komoditas of this Komoditas.


        :param gudang_komoditas: The gudang_komoditas of this Komoditas.
        :type gudang_komoditas: GudangKomoditas
        """

        self._gudang_komoditas = gudang_komoditas

    @property
    def stok(self) -> int:
        """Gets the stok of this Komoditas.


        :return: The stok of this Komoditas.
        :rtype: int
        """
        return self._stok

    @stok.setter
    def stok(self, stok: int):
        """Sets the stok of this Komoditas.


        :param stok: The stok of this Komoditas.
        :type stok: int
        """

        self._stok = stok

    @property
    def nilai_pasar(self) -> int:
        """Gets the nilai_pasar of this Komoditas.


        :return: The nilai_pasar of this Komoditas.
        :rtype: int
        """
        return self._nilai_pasar

    @nilai_pasar.setter
    def nilai_pasar(self, nilai_pasar: int):
        """Sets the nilai_pasar of this Komoditas.


        :param nilai_pasar: The nilai_pasar of this Komoditas.
        :type nilai_pasar: int
        """

        self._nilai_pasar = nilai_pasar
