# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Pembuangan(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, list_barang: List[int]=None, alasan: List[str]=None, status: str=None):  # noqa: E501
        """Pembuangan - a model defined in Swagger

        :param id: The id of this Pembuangan.  # noqa: E501
        :type id: int
        :param list_barang: The list_barang of this Pembuangan.  # noqa: E501
        :type list_barang: List[int]
        :param alasan: The alasan of this Pembuangan.  # noqa: E501
        :type alasan: List[str]
        :param status: The status of this Pembuangan.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': int,
            'list_barang': List[int],
            'alasan': List[str],
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'list_barang': 'list_barang',
            'alasan': 'alasan',
            'status': 'status'
        }
        self._id = id
        self._list_barang = list_barang
        self._alasan = alasan
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Pembuangan':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pembuangan of this Pembuangan.  # noqa: E501
        :rtype: Pembuangan
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Pembuangan.


        :return: The id of this Pembuangan.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Pembuangan.


        :param id: The id of this Pembuangan.
        :type id: int
        """

        self._id = id

    @property
    def list_barang(self) -> List[int]:
        """Gets the list_barang of this Pembuangan.


        :return: The list_barang of this Pembuangan.
        :rtype: List[int]
        """
        return self._list_barang

    @list_barang.setter
    def list_barang(self, list_barang: List[int]):
        """Sets the list_barang of this Pembuangan.


        :param list_barang: The list_barang of this Pembuangan.
        :type list_barang: List[int]
        """

        self._list_barang = list_barang

    @property
    def alasan(self) -> List[str]:
        """Gets the alasan of this Pembuangan.


        :return: The alasan of this Pembuangan.
        :rtype: List[str]
        """
        return self._alasan

    @alasan.setter
    def alasan(self, alasan: List[str]):
        """Sets the alasan of this Pembuangan.


        :param alasan: The alasan of this Pembuangan.
        :type alasan: List[str]
        """

        self._alasan = alasan

    @property
    def status(self) -> str:
        """Gets the status of this Pembuangan.


        :return: The status of this Pembuangan.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Pembuangan.


        :param status: The status of this Pembuangan.
        :type status: str
        """

        self._status = status
