# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Pengguna(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, first_name: str=None, last_name: str=None, email: str=None, date_of_birth: date=None, email_verified: bool=None, create_date: date=None):  # noqa: E501
        """Pengguna - a model defined in Swagger

        :param id: The id of this Pengguna.  # noqa: E501
        :type id: int
        :param first_name: The first_name of this Pengguna.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Pengguna.  # noqa: E501
        :type last_name: str
        :param email: The email of this Pengguna.  # noqa: E501
        :type email: str
        :param date_of_birth: The date_of_birth of this Pengguna.  # noqa: E501
        :type date_of_birth: date
        :param email_verified: The email_verified of this Pengguna.  # noqa: E501
        :type email_verified: bool
        :param create_date: The create_date of this Pengguna.  # noqa: E501
        :type create_date: date
        """
        self.swagger_types = {
            'id': int,
            'first_name': str,
            'last_name': str,
            'email': str,
            'date_of_birth': date,
            'email_verified': bool,
            'create_date': date
        }

        self.attribute_map = {
            'id': 'id',
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email',
            'date_of_birth': 'dateOfBirth',
            'email_verified': 'emailVerified',
            'create_date': 'createDate'
        }
        self._id = id
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._date_of_birth = date_of_birth
        self._email_verified = email_verified
        self._create_date = create_date

    @classmethod
    def from_dict(cls, dikt) -> 'Pengguna':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pengguna of this Pengguna.  # noqa: E501
        :rtype: Pengguna
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Pengguna.

        Unique identifier for the given user.  # noqa: E501

        :return: The id of this Pengguna.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Pengguna.

        Unique identifier for the given user.  # noqa: E501

        :param id: The id of this Pengguna.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Pengguna.


        :return: The first_name of this Pengguna.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Pengguna.


        :param first_name: The first_name of this Pengguna.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Pengguna.


        :return: The last_name of this Pengguna.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Pengguna.


        :param last_name: The last_name of this Pengguna.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self) -> str:
        """Gets the email of this Pengguna.


        :return: The email of this Pengguna.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Pengguna.


        :param email: The email of this Pengguna.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def date_of_birth(self) -> date:
        """Gets the date_of_birth of this Pengguna.


        :return: The date_of_birth of this Pengguna.
        :rtype: date
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth: date):
        """Sets the date_of_birth of this Pengguna.


        :param date_of_birth: The date_of_birth of this Pengguna.
        :type date_of_birth: date
        """

        self._date_of_birth = date_of_birth

    @property
    def email_verified(self) -> bool:
        """Gets the email_verified of this Pengguna.

        Set to true if the user's email has been verified.  # noqa: E501

        :return: The email_verified of this Pengguna.
        :rtype: bool
        """
        return self._email_verified

    @email_verified.setter
    def email_verified(self, email_verified: bool):
        """Sets the email_verified of this Pengguna.

        Set to true if the user's email has been verified.  # noqa: E501

        :param email_verified: The email_verified of this Pengguna.
        :type email_verified: bool
        """
        if email_verified is None:
            raise ValueError("Invalid value for `email_verified`, must not be `None`")  # noqa: E501

        self._email_verified = email_verified

    @property
    def create_date(self) -> date:
        """Gets the create_date of this Pengguna.

        The date that the user was created.  # noqa: E501

        :return: The create_date of this Pengguna.
        :rtype: date
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date: date):
        """Sets the create_date of this Pengguna.

        The date that the user was created.  # noqa: E501

        :param create_date: The create_date of this Pengguna.
        :type create_date: date
        """

        self._create_date = create_date
